### ISSUE TITLE
Shedding >= onset

### ISSUE THREAD

**Issue by seabbs** [adrian-lison/EpiSewer#2]
> Incubation period distribution: Time between infection and symptom onset. It is here assumed that shedding only starts with symptom onset.

From the README. I was wondering what the theoretical support for this was?

**Comment by adrian-lison** [comment]
Thanks for bringing this up @seabbs! It was always just a convenience assumption. This has now partially been relaxed by #19, which makes it easier for users to specify the shedding load distribution either relative to the day of symptom onset (`shedding_reference="symptom_onset"`) or the day of infection (`shedding_reference="infection"`).

What is not yet possible is to have a shedding load distribution by time since symptom onset that has negative support. While such distributions are sometimes given in the literature, it is not straightforward to model them due to the dependence between the incubation period and the shedding load distribution. For example, shedding cannot start three days before symptom onset in a patient with an incubation period of two days. One could theoretically model such a constraint, but I am not sure if the resulting distribution would sufficiently resemble the true joint distribution of incubation period and shedding.

Thoughts welcome!

**Comment by seabbs** [comment]
Ah interesting yes this makes sense when thinking about it in terms of what might be available in the literature. I do think that from infection is likely the better choice if the data is available. 

> One could theoretically model such a constraint, but I am not sure if the resulting distribution would sufficiently resemble the true joint distribution of incubation period and shedding.

I think that this is probably the correct feeling. I am not sure I would be in a rush to support this.
